language: python
python:
  - "2.7"
install:
  - python -m pip install --upgrade pip
  - pip install --upgrade -r requirements.txt --user
script:
  - python -m flake8 --max-line-length=120 core core_tests data products tests
  - python -m nose core_tests\utils -v -s --nologcapture --with-doctest --with-xunit